// app/components/PostListWithPagination.vue
<script setup lang="ts">
import type { PostMeta } from '~/types/post'

const props = defineProps<{
  posts: PostMeta[]
  basePath?: string
}>()

const PAGE_SIZE = 6
const route = useRoute()

const currentPage = computed(() => {
  const raw = route.query.page
  const n = Array.isArray(raw) ? raw[0] : raw
  return Math.max(1, Number(n ?? 1))
})

const totalPages = computed(() => Math.ceil(props.posts.length / PAGE_SIZE))

const pagePosts = computed(() =>
  props.posts.slice((currentPage.value - 1) * PAGE_SIZE, currentPage.value * PAGE_SIZE),
)
</script>

<template>
  <div>
    <div :key="currentPage" class="animate-fade-in">
      <PostCard v-for="post in pagePosts" :key="post.slug" :post="post" />
    </div>
    <Pagination :current-page="currentPage" :total-pages="totalPages" :base-path="basePath ?? '/'" />
  </div>
</template>

// src/components/PostListWithPagination/PostListWithPagination.tsx
'use client';

import { useSearchParams } from 'next/navigation';
import type { PostMeta } from '@/types/post';
import PostCard from '@/components/PostCard/PostCard';
import Pagination from '@/components/Pagination/Pagination';

const PAGE_SIZE = 6;

interface Props {
  posts: PostMeta[];
}

export default function PostListWithPagination({ posts }: Props) {
  const searchParams = useSearchParams();
  const currentPage = Math.max(1, Number(searchParams.get('page') ?? 1));
  const totalPages = Math.ceil(posts.length / PAGE_SIZE);
  const pagePosts = posts.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);

  return (
    <>
      <div key={currentPage} className="animate-fade-in">
        {pagePosts.map((post) => (
          <PostCard key={post.slug} post={post} />
        ))}
      </div>
      <Pagination currentPage={currentPage} totalPages={totalPages} basePath="/" />
    </>
  );
}
